[tool.poetry]
name = "face-detection"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"
opencv-python = "^4.9.0.80"
scipy = "^1.13.0"
matplotlib = "^3.8.4"
numpy = "^1.26.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
